[package]
name = "wispcore"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wisp"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
prisma-client-rust = {workspace = true}
serde =  {version = "1.0"}
tokio = { version = "1.32.0", features = ["full"] }