// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "binder.characters", input: never, result: { id: number; name: string }[] } | 
        { key: "display_tree", input: number, result: TreeData<FamilyTreeNodeData> } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type TreeNode<T> = { id: string; parentId: string | null; hidden: boolean; nodeData: T | null }

export type TreeLinkData = string

export type TreeLink = { source: TreeLinkData; target: TreeLinkData; link: TreeLinkData }

export type TreeData<T> = { nodes: TreeNode<T>[]; links: TreeLink[] }

export type FamilyTreeNodeData = { name: string }
