// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "binder.characters", input: string | null, result: { [key: string]: BinderCharacterPath[] } } | 
        { key: "display_tree", input: number, result: TreeData<FamilyTreeNodeData> } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type FamilyTreeNodeData = { name: string }

export type TreeLink = { source: TreeLinkData; target: TreeLinkData; link: TreeLinkData }

export type TreeNode<T> = { id: string; parentId: string | null; hidden: boolean; nodeData: T | null }

export type BinderCharacterPath = { id: number; isCollection: boolean; path: string; name: string; parentId: number | null; item: { character: Person | null } | null }

export type Person = { id: number; name: string; parentRelationId: number | null; familyId: number | null; binderItemId: number | null }

export type TreeData<T> = { nodes: TreeNode<T>[]; links: TreeLink[] }

export type TreeLinkData = string
